### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by seppelhuang** [ldlood/SpringBoot_Wechat_Sell#8]
Error: Cannot find module './check-versions'
    at Function.Module._resolveFilename (module.
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\workspace\前端代码
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by ldlood** [comment]
你运行npm install的时候有报错吗

**Comment by seppelhuang** [comment]
是不是build目录下少上传了文件？

**Comment by ldlood** [comment]
是的 不好意思啊  发错了版本  我重新上传一个正确的版本

**Comment by seppelhuang** [comment]
多谢，貌似还是旧的版本

**Comment by seppelhuang** [comment]
前端代码删掉啦？

**Comment by ldlood** [comment]
最近加班蛮忙的  就把那个有问题的前端代码删了  今晚弄份完整的前端代码

发自我的 iPhone

在 2017年12月19日，13:25，seppelhuang <notifications@github.com<mailto:notifications@github.com>> 写道：


前端代码删掉啦？

**Comment by sunnuan** [comment]
现在的前端代码是完整的吗？跑起来之后一直不停的刷新，看不到完整的界面
